name = "LowLevelParticleFiltersMTK"
uuid = "6906b499-63f5-4dd8-acfd-28b0f8b24f7d"
authors = ["Fredrik Bagge Carlson"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
